
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arlonctl-2-guestbook
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: arlonctl-2
    namespace: default
  project: default
  source:
    repoURL: https://github.com/jayanth-tjvrr/arlon-test
    path: clusters/arlonctl-2/workload/guestbook
    targetRevision: HEAD
