
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arlonctl-eks-profile-cas-dynamic
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/ShaunakJoshi1407/arlon-demo
    path: profiles/cas-dynamic/mgmt
    targetRevision: HEAD
    helm:
      parameters:
      - name: clusterName
        value: arlonctl-eks
      - name: profileAppName
        value: arlonctl-eks-profile-cas-dynamic
