
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-1-xenial-static
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cluster-1
    namespace: default
  project: default
  source:
    repoURL: https://github.com/jayanth-tjvrr/arlon-test
    path: clusters/cluster-1/workload/xenial-static
    targetRevision: HEAD
