
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-dynamic-eks-redis-profile-dynamic-3
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/jayanth-tjvrr/arlon-test
    path: profiles/dynamic-3/mgmt
    targetRevision: HEAD
    helm:
      parameters:
      - name: clusterName
        value: capi-dynamic-eks-redis
      - name: profileAppName
        value: capi-dynamic-eks-redis-profile-dynamic-3
